name: DEPLOY TO TEST
on:
  push:
    branches: 
      - main

jobs:
  deploy-to-test:
    runs-on: self-hosted
    permissions:
      id-token: write 
      contents: read
#    env:
#     TF_VAR_snowflake_username:  ${{ secrets.SNOWFLAKE_USERNAME_TEST }}
#      TF_VAR_snowflake_account:   ${{ secrets.SNOWFLAKE_ACCOUNT_TEST }}
#     TF_VAR_snowflake_password:  ${{ secrets.SNOWFLAKE_PASSWORD_TEST }}
    steps:
      - name: Checkout repository code 
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        name: setup node
        with:
          node-version: 18

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::256073515130:role/S3accessfotiodc"
          role-session-name: aws-mwaa
          aws-region: "eu-west-1"     

      - uses: hashicorp/setup-terraform@v2
        name: Setup Terraform
        with: 
          terraform_version: 1.4.6
          
      - name: Terraform Init
        run: |
          terraform init -backend-config backend-config-test.tfvars 
        
      - name: Terraform Plan
        run: |
          terraform plan 

 #     - name: Terraform execute
 #       run: |
 #         terraform apply -auto-approve
